services:
  dev-server:
    image: node:18
    init: true
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'

  ssh-client:
    build: ./ssh-client
    init: true
    environment:
      SSH_USER: ec2-user
      SSH_HOST: kddi-xr.churadata.okinawa
      FORWARD_HOST: dev-server
      FORWARD_HOST_PORT: 3000
    volumes:
      - ./ssh-client/ssh_config:/etc/ssh/ssh_config.d/default.conf:ro
      - ./ssh-client/remote_forward.sh:/remote_forward.sh:ro
    command: sh /remote_forward.sh
    secrets:
      - ssh_identity_file